apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: sentrionic/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: sentrionic/products
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: sentrionic/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: sentrionic/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: sentrionic/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.go'
            dest: .
    - image: sentrionic/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .