// Code generated by mockery v2.12.1. DO NOT EDIT.

package publishers

import (
	ent "github.com/sentrionic/ecommerce/products/ent"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockProductPublisher is an autogenerated mock type for the ProductPublisher type
type MockProductPublisher struct {
	mock.Mock
}

// PublishProductCreated provides a mock function with given fields: product
func (_m *MockProductPublisher) PublishProductCreated(product *ent.Product) {
	_m.Called(product)
}

// PublishProductUpdated provides a mock function with given fields: product
func (_m *MockProductPublisher) PublishProductUpdated(product *ent.Product) {
	_m.Called(product)
}

// NewMockProductPublisher creates a new instance of MockProductPublisher. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProductPublisher(t testing.TB) *MockProductPublisher {
	mock := &MockProductPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
