// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Order is the predicate function for entorder builders.
type Order func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)
