apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-postgres
  template:
    metadata:
      labels:
        app: payments-postgres
    spec:
      containers:
        - name: payments-postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: ecommerce
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: payments-postgres-srv
spec:
  selector:
    app: payments-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432