// Code generated by mockery v2.12.1. DO NOT EDIT.

package publishers

import (
	ent "github.com/sentrionic/ecommerce/orders/ent"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockOrderPublisher is an autogenerated mock type for the OrderPublisher type
type MockOrderPublisher struct {
	mock.Mock
}

// PublishOrderCancelled provides a mock function with given fields: order
func (_m *MockOrderPublisher) PublishOrderCancelled(order *ent.Order) {
	_m.Called(order)
}

// PublishOrderCreated provides a mock function with given fields: order, product
func (_m *MockOrderPublisher) PublishOrderCreated(order *ent.Order, product *ent.Product) {
	_m.Called(order, product)
}

// NewMockOrderPublisher creates a new instance of MockOrderPublisher. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOrderPublisher(t testing.TB) *MockOrderPublisher {
	mock := &MockOrderPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
